name: cd
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    spellcheck-docs:
        name: spellcheck and docs
        runs-on: ubuntu-latest
        steps:
            name: spellcheck
            uses: docker://fazenda/rsmd
            run: R -e 'spelling::spell_check_package()'
            name: docs
            uses: docker://fazenda/rsmd
            run: R -e 'devtools::document()'
            name: website
            uses: docker://fazenda/rsmd
            run: R -e 'pkgdown::build_site()'
