name: cd
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    spellcheck-docs:
        name: spellcheck and docs
        runs-on: ubuntu-latest
        steps:
            uses: docker://fazenda/rsmd
            run: |
                R -e 'spelling::spell_check_package()'
                R -e 'devtools::document()'
                R -e 'pkgdown::build_site()'
