name: ci
on:
    push:
        branches:
            - master
            - release
    pull_request:
        branches:
            - master
            - release

jobs:
    test-and-analysis:
        name: test and analysis
        runs-on: ubuntu-latest
        container: docker://fazenda/rsmd
        steps:
            - uses: actions/checkout@v1
            - run: |
                R -e 'devtools::test()'
                R -e 'devtools::check()'
                R -e 'goodpractice::gp()
