name: ci
on:
    push:
        branches:
            - master
            - release
    pull_request:
        branches:
            - master
            - release

jobs:
    test-and-analysis:
        name: test and analysis
        runs-on: ubuntu-latest
        steps:
            uses: docker://fazenda/rsmd
            run: |
                R -e 'devtools::test()'
                R -e 'devtools::check()'
                R -e 'goodpractice::gp()
